### ISSUE TITLE
Not identifying .htaccess file (unable to remove /index.php from URL)

### ISSUE THREAD

**Issue by eappleby** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#114]
WP Version: 6.4.3
PG4WP Version: 3.3.1

Starting with fresh install of Wordpress and when I update the permalink and when I update the URL from /index.php/%year%/%monthnum%/%postname%/ to /%year%/%monthnum%/%postname%/ , it says "The requested URL was not found on this server."

Do you know why that is?

**Comment by mattbucci** [comment]
This doesn't sound related to pg4wp, but rather to your .htaccess file

**Comment by eappleby** [comment]
The htaccess file is autogenerated by Wordpress. The issue is that when I change the permalink structure from anything that doesn’t start with /index.php, it says that the URL is not found on the server. This is a fresh install with no changes other than the permalink structure. Are you not able to replicate that issue?

**Comment by eappleby** [comment]
This was my issue.  Sorry about that. For reference, I used this to correct it: https://stackoverflow.com/a/42736732/1698908 (small typo in my .conf file)
