### ISSUE TITLE
Functions ORDER BY FIELD / ORDER BY RAND not supported?

### ISSUE THREAD

**Issue by aventrax** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#12]
Hello, I successfully installed wp 4.8.2 and migrated my blog. Unfortunately I have 2 issues, the first seems the lack of function ORDER BY FIELD required for the "Galleries". 

My logs:
> [1506246249.4051] Error running :
SELECT   wp_posts.* FROM wp_posts  WHERE 1=1  AND wp_posts.ID IN (1157,1168,1170,1162,1163,1172,1161,1167,1166,1165,1164,1169,1171,1159,1158) AND (wp_posts.post_mime_type LIKE 'image/%')  AND wp_posts.post_type = 'attachment' AND ((wp_posts.post_status = 'inherit' OR wp_posts.post_status = 'private'))  ORDER BY FIELD( wp_posts.ID, 1157,1168,1170,1162,1163,1172,1161,1167,1166,1165,1164,1169,1171,1159,1158 ) 
---- converted to ----
SELECT   wp_posts.* FROM wp_posts  WHERE 1=1  AND wp_posts."ID" IN (1157,1168,1170,1162,1163,1172,1161,1167,1166,1165,1164,1169,1171,1159,1158) AND (wp_posts.post_mime_type ILIKE 'image/%')  AND wp_posts.post_type = 'attachment' AND ((wp_posts.post_status = 'inherit' OR wp_posts.post_status = 'private'))  ORDER BY FIELD( wp_posts."ID" , 1157,1168,1170,1162,1163,1172,1161,1167,1166,1165,1164,1169,1171,1159,1158 )
----> ERROR:  function field(bigint, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer) does not exist
LINE 1: ...' OR wp_posts.post_status = 'private'))  ORDER BY FIELD( wp_...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

The second issue is about a widget requiring the ORDER BY RAND. The widget shows random images from my library.

> [1506246492.6643] Error running :
SELECT   wp_posts.ID FROM wp_posts  WHERE 1=1  AND (wp_posts.post_mime_type LIKE 'image/%')  AND wp_posts.post_type = 'attachment' AND ((wp_posts.post_status = 'inherit'))  ORDER BY RAND() LIMIT 0, 10
---- converted to ----
SELECT   wp_posts."ID" FROM wp_posts  WHERE 1=1  AND (wp_posts.post_mime_type ILIKE 'image/%')  AND wp_posts.post_type = 'attachment' AND ((wp_posts.post_status = 'inherit'))  ORDER BY RAND() LIMIT 10 OFFSET 0
----> ERROR:  function rand() does not exist
LINE 1: ...ND ((wp_posts.post_status = 'inherit'))  ORDER BY RAND() LIM...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

I know  postgres is not supported and you probably did this wrapper for your use, unfortunately I have not enough knowledge to import theese functions by me. I'm opening this issue, if one day you will implement this I'll be happy :)

Thanks!

**Comment by kevinoid** [comment]
Sure, those seem pretty straight-forward.  Thanks for taking the time to review the logs and isolate the issues.  I've added fixes for `FIELD` in f896bb1 and `RAND` in 54042c1.  Give it a try and feel free to reopen the issue if those don't fix it for you.

**Comment by aventrax** [comment]
Thank you very much, I didn't hope to have this implemented at all, so after few hours is very impressive :) Due to this reason, I removed the test environment, so now I'm starting again but I have an error that prevent me from installing wordpress. 

> 2017/09/24 23:27:47 [error] 17094#17094: *337268 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare pg4wp_rewrite_field() (previously declared in /var/www/site/wp-content/pg4wp/driver_pgsql.php:287) in /var/www/site/wp-content/pg4wp/driver_pgsql.php on line 287" while reading response header from upstream, client: 2001:.........., server: site.example.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "..."

Going back to the previous release, the issue goes away and I can install it.

Thanks again!

**Comment by kevinoid** [comment]
Sure thing.  Glad it turned out to be an easy fix!

Good catch.  I forgot about how redefinition of non-anonymous functions works and didn't test thoroughly enough.  Just pushed a fix in 06884bd.  Should be fixed now.

**Comment by aventrax** [comment]
Great. Everything is working now. I'm really near to keep postgres in "production".
Doing this migration helped me to understand many things in postgres and the db structure that WP create/use, so I'm more confident in future to be able to go back to mysql in case problems will arise.
Thank you again for supporting this plugin.
