### ISSUE TITLE
PG4WP directory not in WordPress 5.4

### ISSUE THREAD

**Issue by vaidehi-imedia** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#17]
Hi,

I am downloaded latest version WordPress and followed steps given on your link for installing WordPress with PostgreSQL But I am not getting error "PG4WP file directory not found"

Can you let me know what is the error I am making?

Thanks

**Comment by kevinoid** [comment]
Is there a `pg4wp` (lower-case) directory inside the `wp-content` directory of your site?  Does that directory contain PHP files?

FYI, this is not a project that I'm currently supporting.  I have only posted the changes that I've made for my own use and occasionally answer questions or merge updates as I have time.  Based on your question, it is very likely, especially if you use plugins, that you'll encounter issues you can't debug or fix.  I would advise you to strongly reconsider whether using pg4wp is appropriate for your site.

**Comment by Christian-Kamdem** [comment]
@vaidehi-imedia You should rename the folder with lower case characters. "pg4wp" instead of "Pg4wp"
