### ISSUE TITLE
Arm64 Deploy

### ISSUE THREAD

**Issue by r1200gsdave** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#23]
I am trying to deploy on an Arm kubernetes cluster.  The image image: arm64v8/wordpress works.  How do I put these customizations in it?

**Comment by kevinoid** [comment]
Presumably by following the steps in the Installation section of [readme.txt](https://github.com/kevinoid/postgresql-for-wordpress/blob/wordpress4-compat/readme.txt) in your container image.  If you are not familiar with how to do so, perhaps a Kubernetes or Docker forum would be a better place to ask for assistance?
