### ISSUE TITLE
Failed to open stream: No such file or directory in /var/www/html/wp-content/pg4wp/core.php(34) 

### ISSUE THREAD

**Issue by beacon-hash** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#24]
I face the following error when trying to access the site:

`[Wed Feb 15 05:32:51.857483 2023] [php:warn] [pid 23] [client 10.0.0.1:42416] PHP Warning:  require_once(/var/www/html/wp-content/pg4wp/class-wpdb.php): Failed to open stream: No such file or directory in /var/www/html/wp-content/pg4wp/core.php(34) : eval()'d code on line 17
[Wed Feb 15 05:32:51.857515 2023] [php:error] [pid 23] [client 10.0.0.1:42416] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/wp-content/pg4wp/class-wpdb.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/pg4wp/core.php(34) : eval()'d code:17\nStack trace:\n#0 /var/www/html/wp-content/pg4wp/core.php(34): eval()\n#1 /var/www/html/wp-content/db.php(39): require_once('/var/www/html/w...')\n#2 /var/www/html/wp-includes/load.php(550): require_once('/var/www/html/w...')\n#3 /var/www/html/wp-settings.php(124): require_wp_db()\n#4 /var/www/html/wp-config.php(133): require_once('/var/www/html/w...')\n#5 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')\n#6 /var/www/html/wp-blog-header.php(13): require_once('/var/www/html/w...')\n#7 /var/www/html/index.php(17): require('/var/www/html/w...')\n#8 {main}\n  thrown in /var/www/html/wp-content/pg4wp/core.php(34) : eval()'d code on line 17
10.0.0.1 - - [15/Feb/2023:05:32:51 +0000] "GET / HTTP/1.1" 500 2973 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
[Wed Feb 15 05:32:51.865540 2023] [php:warn] [pid 19] [client 10.0.0.1:42432] PHP Warning:  require_once(/var/www/html/wp-content/pg4wp/class-wpdb.php): Failed to open stream: No such file or directory in /var/www/html/wp-content/pg4wp/core.php(34) : eval()'d code on line 17, referer: http://10.0.0.2/
[Wed Feb 15 05:32:51.865570 2023] [php:error] [pid 19] [client 10.0.0.1:42432] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/wp-content/pg4wp/class-wpdb.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/pg4wp/core.php(34) : eval()'d code:17\nStack trace:\n#0 /var/www/html/wp-content/pg4wp/core.php(34): eval()\n#1 /var/www/html/wp-content/db.php(39): require_once('/var/www/html/w...')\n#2 /var/www/html/wp-includes/load.php(550): require_once('/var/www/html/w...')\n#3 /var/www/html/wp-settings.php(124): require_wp_db()\n#4 /var/www/html/wp-config.php(133): require_once('/var/www/html/w...')\n#5 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')\n#6 /var/www/html/wp-blog-header.php(13): require_once('/var/www/html/w...')\n#7 /var/www/html/index.php(17): require('/var/www/html/w...')\n#8 {main}\n  thrown in /var/www/html/wp-content/pg4wp/core.php(34) : eval()'d code on line 17, referer: http://10.0.0.2/
10.0.0.1 - - [15/Feb/2023:05:32:51 +0000] "GET /favicon.ico HTTP/1.1" 500 2973 "http://10.0.0.2/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
`

Wordpress version: 6.1.1

**Comment by girorme** [comment]
@beacon-hash hi bro! You can solve the issue updating the core manually:

Update the line in `wp-content/pg4wp/core.php:34`:

from:
```
eval( str_replace( array_keys($replaces), array_values($replaces), file_get_contents(ABSPATH.'/wp-includes/wp-db.php')));
```

to:
```
eval( str_replace( array_keys($replaces), array_values($replaces), file_get_contents(ABSPATH.'/wp-includes/class-wpdb.php')))
```

**Comment by mattbucci** [comment]
fixed in v1 and v2 branches
