### ISSUE TITLE
WordPress 6.2 is not supported

### ISSUE THREAD

**Issue by piotrmaslanka** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#25]
I just tested your software, trying to get upgraded to 6.2.

No ball.

Looks like WordPress are bringing [their own DB abstractions](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wpdb.php) and an unfunny adventure to rewrite 4k lines of code is looking as bright as ever :)

I'm sticking to 5.8. These were the  error messages: 
![image](https://user-images.githubusercontent.com/103189/231254234-7698245f-285f-4fd9-a9a7-f8da39de8aaa.png)

**Comment by mattbucci** [comment]
fixed in v1 and v2 branches.
