### ISSUE TITLE
pg4wp is completely dead

### ISSUE THREAD

**Issue by unknown-gd** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#27]
#### I appeal to author to either remove this pointless monument of his laziness, or write in `README.md` that the project is abandoned, or at least send this repository to archive.

Good luck everyone, `mysql` seems to be our only option for a stable wordpress installation right now.

**Comment by mattbucci** [comment]
I was able to revive the code in this plugin and get a base install working on PHP 8.1 with WP 6+
https://github.com/kevinoid/postgresql-for-wordpress/pull/31
