### ISSUE TITLE
Support for Wordpress 4?

### ISSUE THREAD

**Issue by garak** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#3]
Latest version of Wordpress is 4.5.2, is there any chance to get this plugin working?

**Comment by kevinoid** [comment]
Sure, I'll take a look at it later this week.

Have you tried it?  Did you encounter errors?

**Comment by garak** [comment]
Didn't try it, just stopped as long as I read `Tested up to: 3.4`.

**Comment by garak** [comment]
Any news on this?

**Comment by kevinoid** [comment]
I just did a fresh install with Wordpress 4.5.3 and fixed a couple of warnings.  Everything worked well with two exceptions:
- The `wp-config.php` file must be created manually if it does not already exist.  Unfortunately, `require_wp_db` only loads `db.php` on the first call.  So when `setup-config.php` unsets `$wpdb` and calls it again there's no way for us to set a custom value.
- If debugging is enabled in Wordpress, it logs some warnings that the `wp_options` table does not exist before it is created.  This doesn't appear to be a pg4wp issue, but I have not looked closely.

That being said, the testing I've done is pretty minimal.  So although it should work, I wouldn't recommend it unless you are comfortable debugging any issues that may arise.  If you are, then have at it!

**Comment by kevinoid** [comment]
i hope you've had good luck if you've decided to move forward with pg4wp.  I opened #4 to track the installation issue with `wp-config.php`.  If you run into any other issues, feel free to submit them.

If I've overlooked anything that remains from this one, feel free to reopen it.  Otherwise, I'll consider it closed.  Thanks!
