### ISSUE TITLE
field function not available in postgresql

### ISSUE THREAD

**Issue by mmaenz** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#8]
While setup, the function "field" should be created as it is not available in postgresql. It is needed by wp and often seen in the error-log. Making galleries for example is impossible without.

Here is code for creating field function as needed:
CREATE OR REPLACE FUNCTION field(BIGINT, VARIADIC anyarray) RETURNS BIGINT AS $$
				SELECT n FROM (
   			 	SELECT ROW_NUMBER() OVER () AS n, x FROM unnest($2) x)
   			 	 numbered WHERE numbered.x = $1;
			$$ LANGUAGE sql IMMUTABLE STRICT;

I'm not an expert, but just worked for me...

Thanks!
(Using WP 4.7.3 with postgres 9.3.5)

**Comment by kevinoid** [comment]
Sounds good, thanks for the report.  I made a couple changes to the `field` function (e.g. returning 0 on no match) for better MySQL compatibility.  Let me know if that doesn't fix the issue for you.
