### ISSUE TITLE
$dbname is not used in driver_pgsql.php

### ISSUE THREAD

**Issue by waffleboot** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#87]
Hi, it looks it's an error

driver_pgsql.php @ 103

```
$dbname = defined('DB_NAME') && DB_NAME ? DB_NAME : $database;
$pg_connstr = $GLOBALS['pg4wp_connstr'] . ' dbname=' . $database;
```

`$dbname` is not used and `$pg_connstr` is constructed with `$database` instead of `$dbname`

**Comment by mattbucci** [comment]
Duplicate of https://github.com/PostgreSQL-For-Wordpress/postgresql-for-wordpress/issues/74 so it closes that one too
