### ISSUE TITLE
Having problems with SELECT DISTINCT and missing GROUP BY

### ISSUE THREAD

**Issue by mmaenz** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#9]
Hi,

Distinctive selects are not working as postgresql expects GROUP BY after WHERE clause.
Didn't manage to get it working.

Possibly you can create a patch?

Thanks!

(Using WP 4.7.3 with postgres 9.3.5)

**Comment by kevinoid** [comment]
Thanks for the report.  Are you saying there is a query with `GROUP BY` before `WHERE`?  If so, could you provide the problematic query or clarify how to reproduce the issue (e.g. what plugin or series of configuration options will cause the query to be run)?

Thanks.

**Comment by mmaenz** [comment]
No, not directly. The error message is:
[08-Apr-2017 17:29:46 UTC] WordPress-Database-Error ERROR: column "wp_postmeta.meta_key" must appear in the GROUP BY clause or be used in an  aggregate function 
LINE 1: 
**SELECT DISTINCT meta_key**
                        _^ For query SELECT DISTINCT meta_key_
			**FROM wp_postmeta
			WHERE meta_key NOT BETWEEN '_' AND '_z'
			HAVING meta_key NOT LIKE '\_%'
			ORDER BY meta_key
			LIMIT 30** 
from include('...\wordpress\wp-admin\edit-form-advanced.php'), do_meta_boxes, call_user_func, post_custom_meta_box, meta_form

If I run the query with GROUP BY meta_key after the WHERE and before the HAVING it works. But I can't get it to work by myself. Just used pgAdmin to troubleshoot. Tried changing the rewrite sql function in driver_pgsql.php without success.

Thanks!

**Comment by kevinoid** [comment]
Sorry for the delay.  This should be fixed now.  Let me know if that doesn't fix the issue for you.

**Comment by mmaenz** [comment]
Works like a charm! Thank you!!
